server:
  port: ${SERVER_PORT:29030}  # 服务端口，可通过环境变量动态配置，默认29030

spring:
  application:
    name: newbee-mall-cloud-shop-cart-service  # 服务名称

  # 数据源配置 (MySQL)
  datasource:
    name: newbee-mall-cloud-shop-cart-datasource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:newbee_mall_cloud_cart_db}?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
    username: ${DB_USERNAME:root}  # 数据库用户名
    password: ${DB_PASSWORD:123456}  # 数据库密码
    type: com.alibaba.druid.pool.DruidDataSource  # 使用 Druid 数据源
    druid:
      initialSize: 10
      minIdle: 5
      maxActive: 30
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false

  # MyBatis 配置
  mybatis:
    mapper-locations: classpath:mapper/*Mapper.xml

  # Redis 配置
  redis:
    database: 0  # Redis 数据库索引
    host: ${REDIS_HOST:127.0.0.1}  # Redis服务器地址
    port: ${REDIS_PORT:6379}  # Redis服务器端口
    password: ${REDIS_PASSWORD:123456789}
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 5000

  # Sleuth 配置
  sleuth:
    sampler:
      probability: 1.0  # Sleuth 采样率
      rate: 500  # 每秒数据采集量

  # Zipkin 配置
  zipkin:
    base-url: ${ZIPKIN_BASE_URL:http://localhost:9411}  # Zipkin服务地址

  # Sentinel 配置
  cloud:
    sentinel:
      transport:
        port: 8930
        clientIp: 127.0.0.1
        dashboard: ${SENTINEL_DASHBOARD:127.0.0.1:9113}  # Sentinel控制台地址

# OpenFeign 配置
feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 5000
    compression:
      request:
        enabled: true
        mime-types: text/xml, application/xml, application/json
        min-request-size: 1024
      response:
        enabled: true

# Seata 配置
seata:
  enabled: true
  application-id: shopcart-server
  tx-service-group: ${SEATA_TX_GROUP:newbee_cloud_save_order_group}
  registry:
    type: kubernetes  # 使用 Kubernetes 服务发现
  service:
    vgroupMapping:
      newbee_cloud_save_order_group: "default"
    grouplist:
      default: seata-server.default.svc.cluster.local:8091  # Kubernetes服务地址
    enable-degrade: false
    disable-global-transaction: false

# 日志级别
logging:
  level:
    ltd:
      shopcart:
        cloud:
          newbee: debug  # 设置为debug级别