server:
  port: ${SERVER_PORT:29010}  # 服务端口，可通过环境变量动态配置，默认29010

spring:
  application:
    name: shopease-mall-cloud-goods-service  # 服务名称

  # 数据源配置 (MySQL)
  datasource:
    name: shopease-mall-cloud-goods-datasource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:shopease_mall_cloud_goods_db}?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
    username: ${DB_USERNAME:root}  # 数据库用户名
    password: ${DB_PASSWORD:123456}  # 数据库密码
    type: com.alibaba.druid.pool.DruidDataSource  # 使用 Druid 数据源
    druid:
      initialSize: 10
      minIdle: 5
      maxActive: 30
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false

  # Sentinel 配置
  cloud:
    sentinel:
      transport:
        port: 8910
        clientIp: 127.0.0.1
        dashboard: ${SENTINEL_DASHBOARD:127.0.0.1:9113}  # Sentinel控制台地址

  # Zipkin 配置
  zipkin:
    base-url: ${ZIPKIN_BASE_URL:http://localhost:9411}  # Zipkin服务地址

  # Sleuth 配置
  sleuth:
    sampler:
      probability: 1.0  # Sleuth 采样率
      rate: 500  # 每秒数据采集量

  # MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

# OpenFeign 配置
feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 5000
    compression:
      request:
        enabled: true
        mime-types: text/xml, application/xml, application/json
        min-request-size: 1024
      response:
        enabled: true
  ribbon:
    enabled: false  # 禁用 Ribbon

# Seata 配置
seata:
  enabled: true
  application-id: goods-server
  tx-service-group: ${SEATA_TX_GROUP:shopease_cloud_save_order_group}
  registry:
    type: file  # 使用文件方式做服务发现
  service:
    vgroupMapping:
      shopease_cloud_save_order_group: "default"
    grouplist:
      default: seata.default.svc.cluster.local:8091 # Kubernetes服务发现地址
    enable-degrade: false
    disable-global-transaction: false

# 日志级别配置
logging:
  level:
    ltd:
      goods:
        cloud:
          shopease: debug  # 设置为debug级别
# Aliyun OSS Configuration
aliyun:
  oss:
    end-point: oss-ap-southeast-1.aliyuncs.com
    key-id: ${ALIYUN_OSS_KEY_ID}
    key-secret: ${ALIYUN_OSS_KEY_SECRET}
    bucket-name: shopease-mall