apiVersion: apps/v1
kind: Deployment
metadata:
  name: mall-admin-deployment
  labels:
    admin: mall-admin
spec:
  replicas: 1  # Nginx 实例副本数量
  selector:
    matchLabels:
      admin: mall-admin
  template:
    metadata:
      labels:
        admin: mall-admin
    spec:
      containers:
      - name: mall-admin
        image: hangtang/mall-admin:latest # 使用官方 Nginx 镜像
        ports:
        - containerPort: 80  # Nginx 监听的端口

---
apiVersion: v1
kind: Service
metadata:
  name: mall-admin-external
spec:
  type: LoadBalancer  # 选择 LoadBalancer
  selector:
    admin: mall-admin
  ports:
    - port: 80       # 公开的端口
      targetPort: 80 # 容器内部的端口
