apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  ports:
    - port: 29040  # 外部访问的端口
      targetPort: 29040  # 应用容器的端口
      protocol: TCP
  selector:
    app: order-service
  type: ClusterIP  # 可以使用 NodePort 或 LoadBalancer 根据你的需求来暴露服务