apiVersion: v1
kind: Service
metadata:
  name: recommend-service
  labels:
    app: recommend-service
spec:
  ports:
    - port: 29020  # 服务端口
      targetPort: 29020  # 容器内部端口
  selector:
    app: recommend-service
  type: ClusterIP
