apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommend-service
  labels:
    app: recommend-service
spec:
  replicas: 1  # 副本数量，可根据需要调整
  selector:
    matchLabels:
      app: recommend-service
  template:
    metadata:
      labels:
        app: recommend-service
    spec:
      containers:
        - name: recommend-service
          image: roderickyoung/recommend-service:lastest  # 请替换为你的镜像地址
          ports:
            - containerPort: 8080  # 容器内的应用服务端口
          env:
            - name: SERVER_PORT
              value: "29000"  # 服务端口
            - name: DB_HOST
              value: "mysql"  # Kubernetes 中 MySQL 的服务名称
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "newbee_mall_cloud_recommend_db"  # 数据库名称
            - name: DB_USERNAME
              value: "root"  # 数据库用户名
            - name: DB_PASSWORD
              value: "123456"  # 数据库密码
            - name: ZIPKIN_BASE_URL
              value: "http://zipkin:9411"  # Zipkin 服务地址
            - name: SENTINEL_DASHBOARD
              value: "sentinel:9113"  # Sentinel 控制台地址
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"