apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommend-service
  labels:
    app: recommend-service
spec:
  selector:
    matchLabels:
      app: recommend-service
  template:
    metadata:
      labels:
        app: recommend-service
    spec:
      containers:
        - name: recommend-service
          image: roderickyoung/shopease:recommend-service-1.0.0
          imagePullPolicy: Always


          ports:
            - containerPort: 29020  # 容器内的应用服务端口
          env:
            - name: SERVER_PORT
              value: "29020"  # 服务端口
            - name: DB_HOST
              value: "mysql"  # Kubernetes 中 MySQL 的服务名称
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "shopease_mall_cloud_recommend_db"  # 数据库名称
            - name: DB_USERNAME
              value: "root"  # 数据库用户名
            - name: DB_PASSWORD
              value: "123456"  # 数据库密码
            - name: ZIPKIN_BASE_URL
              value: "http://zipkin:9411"  # Zipkin 服务地址
            - name: SENTINEL_DASHBOARD
              value: "sentinel:9113"  # Sentinel 控制台地址
          resources:
            requests:
              cpu: "1000m"
              memory: "200Mi"
            limits:
              cpu: "1500m"
              memory: "1000Mi"
