apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-cart-service
spec:
  selector:
    matchLabels:
      app: shop-cart-service
  template:
    metadata:
      labels:
        app: shop-cart-service
    spec:
      containers:
        - name: shop-cart-service
          image: roderickyoung/shopease:shop-cart-service-1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 29030
          resources:
            requests:
              cpu: "400m"
              memory: "2Mi"
            limits:
              cpu: "1000m"
              memory: "800Mi"
          env:
            - name: SERVER_PORT
              value: "29030"  # 服务端口
            - name: DB_HOST
              value: "mysql"  # Kubernetes中MySQL的服务名称
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "newbee_mall_cloud_cart_db"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              value: "123456"
            - name: REDIS_HOST
              value: "redis"  # Kubernetes中Redis的服务名称
            - name: REDIS_PORT
              value: "6379"
            - name: ZIPKIN_BASE_URL
              value: "http://zipkin:9411"  # Kubernetes中Zipkin的服务地址
            - name: SENTINEL_DASHBOARD
              value: "sentinel:9113"  # Kubernetes中Sentinel的服务地址
            - name: SEATA_TX_GROUP
              value: "newbee_cloud_save_order_group"  # Seata事务组