apiVersion: v1
kind: Service
metadata:
  name: shop-cart-service
  labels:
    app: shop-cart-service
spec:
  selector:
    app: shop-cart-service  # 与 Deployment 中的 label 匹配
  ports:
    - protocol: TCP
      port: 29030  # Kubernetes 服务的端口
      targetPort: 29030  # 容器内部的端口
  type: ClusterIP  # 服务类型，默认为内部服务。可以根据需要选择 NodePort 或 LoadBalancer 来暴露给外部