apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 29000
      targetPort: 29000
  type: ClusterIP  # 根据需求选择 Service 类型，如 ClusterIP、NodePort 或 LoadBalancer