apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
    - name: http
      protocol: TCP
      port: 9200  # 外部访问的端口
      targetPort: 9200  # Elasticsearch HTTP端口
    - name: transport
      protocol: TCP
      port: 9300  # 外部访问的端口 (集群通信)
      targetPort: 9300  # Elasticsearch 集群通信端口
  type: ClusterIP  # 可根据需求更改为 NodePort 或 LoadBalancer