apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      initContainers: # 添加 initContainer 来修复权限问题
        - name: fix-elasticsearch-permissions
          image: busybox
          command: [ "sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data" ]
          volumeMounts:
            - name: elasticsearch-storage
              mountPath: /usr/share/elasticsearch/data
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - elasticsearch
                      - logstash
                      - kibana
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
          ports:
            - containerPort: 9200  # Elasticsearch HTTP端口
            - containerPort: 9300  # 集群通信端口
          env:
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: "-Xms512M -Xmx512M"  # 设置最小和最大JVM内存为1GB
          resources:
            requests:
              cpu: "20m"
              memory: "300Mi"
            limits:
              cpu: "100m"
              memory: "1Gi"

          volumeMounts:
            - name: elasticsearch-storage
              mountPath: /usr/share/elasticsearch/data  # ES数据目录
      volumes:
        - name: elasticsearch-storage
          persistentVolumeClaim:
            claimName: elasticsearch-pvc