apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  ports:
    - port: 5601
      targetPort: 5601
  selector:
    app: kibana
  type: ClusterIP  # 如果需要外部访问 Kibana，可以改为 NodePort 或 LoadBalancer