apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: default
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
            volumeMounts:
              - name: mysql-storage
                mountPath: /var/lib/mysql  # MySQL数据目录
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc


# PVC to be added