apiVersion: apps/v1
kind: Deployment
metadata:
  name: mall-app-deployment
  labels:
    app: mall-app
spec:
  replicas: 2  # Nginx 实例副本数量
  selector:
    matchLabels:
      app: mall-app
  template:
    metadata:
      labels:
        app: mall-app
    spec:
      containers:
      - name: mall-app
        image: hangtang/mall-app:latest # 使用官方 Nginx 镜像
        ports:
        - containerPort: 80  # Nginx 监听的端口

---
apiVersion: v1
kind: Service
metadata:
  name: mall-app-external
spec:
  type: LoadBalancer  # 选择 LoadBalancer 或 NodePort
  selector:
    app: mall-app
  ports:
    - port: 80       # 公开的端口
      targetPort: 80 # 容器内部的端口
