server:
  port: ${SERVER_PORT:29020}  # 服务端口，可通过环境变量动态配置，默认29000

spring:
  application:
    name: newbee-mall-cloud-recommend-service  # 服务名称
  cloud:
    sentinel:
      transport:
        port: 29020
        clientIp: 127.0.0.1
        dashboard: ${SENTINEL_DASHBOARD:127.0.0.1:9113}  # Sentinel控制台地址
  sleuth:
    sampler:
      probability: 1.0  # Sleuth采样率
      rate: 500  # 每秒数据采集量
  zipkin:
    base-url: ${ZIPKIN_BASE_URL:http://localhost:9411}  # Zipkin服务地址

  # 数据源配置 (MySQL)
  datasource:
    name: newbee-mall-cloud-recommend-datasource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:newbee_mall_cloud_user_db}?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
    username: ${DB_USERNAME:root}  # 数据库用户名
    password: ${DB_PASSWORD:123456}  # 数据库密码
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 60000
      pool-name: hikariCP
      max-lifetime: 600000
      connection-timeout: 30000
      connection-test-query: SELECT 1

# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

# OpenFeign 配置
feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 5000
    compression:
      request:
        enabled: true
        mime-types: text/xml,application/xml,application/json
        min-request-size: 1024
      response:
        enabled: true
