# HPA for user-service
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-service
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 40

---
# HPA for goods-service
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: goods-service-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: goods-service
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

---
# HPA for order-service
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: order-service-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: order-service
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 40

---
# HPA for order-service
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: recommend-service-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: recommend-service
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 40


---
# HPA for order-service
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: shop-cart-service-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shop-cart-service
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 40