apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-ingress-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mall-app-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60