name: Cloud Native CI/CD

on:
  push:
    branches:
      - main  # 监听 main 分支

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 8  # 使用 Java 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

  quality-test:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $SNYK_TOKEN

      - name: Run Snyk to check for vulnerabilities
        run: |
          cd back-end
          snyk test --severity-threshold=high || true

  maven-build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build with Maven
        run: mvn clean package -DskipTests

  docker-push:
    runs-on: ubuntu-latest
    needs: maven-build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker images
        run: |
          docker build -t roderickyoung/shopease:shop-cart-service-1.0.0 newbee-mall-cloud-shop-cart-service
          docker push roderickyoung/shopease:shop-cart-service-1.0.0
          
          docker build -t roderickyoung/shopease:user-service-1.0.0 newbee-mall-cloud-user-service
          docker push roderickyoung/shopease:user-service-1.0.0

          docker build -t roderickyoung/shopease:order-service-1.0.0 newbee-mall-cloud-order-service
          docker push roderickyoung/shopease:order-service-1.0.0

          docker build -t roderickyoung/shopease:recommend-service-1.0.0 newbee-mall-cloud-recommend-service
          docker push roderickyoung/shopease:recommend-service-1.0.0

          docker build -t roderickyoung/shopease:goods-service-1.0.0 newbee-mall-cloud-goods-service
          docker push roderickyoung/shopease:goods-service-1.0.0