name: Cloud Native CI/CD

on:
  push:
    branches:
      - main  # 监听 main 分支

jobs:
  maven-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["newbee-mall-cloud-shop-cart-service",
                  "newbee-mall-cloud-user-service",
                  "newbee-mall-cloud-order-service",
                  "newbee-mall-cloud-recommend-service",
                  "newbee-mall-cloud-goods-service"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 8  # 使用 Java 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Maven build
        run: |
          # 进入相应服务目录，执行 Maven 打包
          cd ./${{ matrix.service }}
          mvn clean package -DskipTests

  docker-build-and-push:
    needs: maven-build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["newbee-mall-cloud-shop-cart-service",
                  "newbee-mall-cloud-user-service",
                  "newbee-mall-cloud-order-service",
                  "newbee-mall-cloud-recommend-service",
                  "newbee-mall-cloud-goods-service"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and push Docker image
        run: |
          # 使用 Bash 的参数展开移除 'newbee-mall-cloud' 前缀
          IMAGE_NAME=${{ matrix.service }}
          IMAGE_NAME=${IMAGE_NAME#newbee-mall-cloud-}
          
          # 构建变更的服务镜像并推送到 DockerHub
          docker build -t roderickyoung/shopease:${IMAGE_NAME}-1.0.0 ./newbee-mall-cloud/${{ matrix.service }}
          
          # 推送到 DockerHub
          docker push roderickyoung/shopease:${IMAGE_NAME}-1.0.0