name: Cloud Native CI/CD

on:
  push:
    branches:
      - main  # 监听 main 分支

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

  cache-maven:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

  setup-java:
    runs-on: ubuntu-latest
    needs: cache-maven
    steps:
      - name: Set up JDK 8  # 使用 Java 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

  build-maven:
    runs-on: ubuntu-latest
    needs: setup-java
    steps:
      - name: Build with Maven
        run: mvn clean package -DskipTests

  docker-login:
    runs-on: ubuntu-latest
    needs: build-maven
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  build-docker-images:
    runs-on: ubuntu-latest
    needs: docker-login
    steps:
      - name: Build Docker image
        run: |
          docker build -t roderickyoung/shopease:shop-cart-service-1.0.0 newbee-mall-cloud-shop-cart-service
          docker build -t roderickyoung/shopease:user-service-1.0.0 newbee-mall-cloud-user-service
          docker build -t roderickyoung/shopease:order-service-1.0.0 newbee-mall-cloud-order-service
          docker build -t roderickyoung/shopease:recommend-service-1.0.0 newbee-mall-cloud-recommend-service
          docker build -t roderickyoung/shopease:goods-service-1.0.0 newbee-mall-cloud-goods-service

  push-docker-images:
    runs-on: ubuntu-latest
    needs: build-docker-images
    steps:
      - name: Push Docker image
        run: |
          docker push roderickyoung/shopease:shop-cart-service-1.0.0
          docker push roderickyoung/shopease:user-service-1.0.0
          docker push roderickyoung/shopease:order-service-1.0.0
          docker push roderickyoung/shopease:recommend-service-1.0.0
          docker push roderickyoung/shopease:goods-service-1.0.0