name: Cloud Native CI/CD

on:
  push:
    branches:
      - main  # 监听 main 分支

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

  cache-maven:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

  build-maven:
    runs-on: ubuntu-latest
    needs: [checkout, cache-maven]
    steps:
      - name: Set up JDK 8  # 使用 Java 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package -DskipTests

  build-docker-shop-cart:
    runs-on: ubuntu-latest
    needs: build-maven
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for shop-cart-service
        run: docker build -t roderickyoung/shopease:shop-cart-service-1.0.0 newbee-mall-cloud-shop-cart-service

      - name: Push Docker image for shop-cart-service
        run: docker push roderickyoung/shopease:shop-cart-service-1.0.0

  build-docker-user:
    runs-on: ubuntu-latest
    needs: build-maven
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for user-service
        run: docker build -t roderickyoung/shopease:user-service-1.0.0 newbee-mall-cloud-user-service

      - name: Push Docker image for user-service
        run: docker push roderickyoung/shopease:user-service-1.0.0

  build-docker-order:
    runs-on: ubuntu-latest
    needs: build-maven
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for order-service
        run: docker build -t roderickyoung/shopease:order-service-1.0.0 newbee-mall-cloud-order-service

      - name: Push Docker image for order-service
        run: docker push roderickyoung/shopease:order-service-1.0.0

  build-docker-recommend:
    runs-on: ubuntu-latest
    needs: build-maven
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for recommend-service
        run: docker build -t roderickyoung/shopease:recommend-service-1.0.0 newbee-mall-cloud-recommend-service

      - name: Push Docker image for recommend-service
        run: docker push roderickyoung/shopease:recommend-service-1.0.0

  build-docker-goods:
    runs-on: ubuntu-latest
    needs: build-maven
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for goods-service
        run: docker build -t roderickyoung/shopease:goods-service-1.0.0 newbee-mall-cloud-goods-service

      - name: Push Docker image for goods-service
        run: docker push roderickyoung/shopease:goods-service-1.0.0